superzanti/ServerSync

.gitignore
So your commits don't get all spammed with gradle logs, class builds and all the other crap that they are currently filled with.
=> Make a gitignore

src/main/java/com/superzanti/serversync/ServerSyncRegistry.java, src/main/java/com/superzanti/serversync/SyncClient.java, src/main/java/com/superzanti/serversync/SyncClientConnection.java, src/main/java/runme/Delete.java, src/main/java/runme/Main.java
Runs a task on exit that deletes remaining files.
=> Better temp fix for windows issues

README.md, src/main/java/com/superzanti/serversync/ClientWorker.java, src/main/java/com/superzanti/serversync/ServerSetup.java, src/main/java/com/superzanti/serversync/ServerWorker.java, src/main/java/com/superzanti/serversync/SyncConfig.java, src/main/java/com/superzanti/serversync/util/MCConfigReader/MCCArray.java, src/main/java/com/superzanti/serversync/util/MCConfigReader/MCCElement.java, src/main/java/com/superzanti/serversync/util/MCConfigReader/MCCReader.java, src/main/java/com/superzanti/serversync/util/MCConfigReader/MCCWriter.java, src/main/java/com/superzanti/serversync/util/Server.java, src/main/java/runme/Main.java
Changed configs to be separate on client and server and changed the values accordingly.
Clients have the ability to refuse pushed client only mods from the server.
=> Updated config handling

src/main/java/com/superzanti/serversync/ServerSetup.java, src/main/java/com/superzanti/serversync/ServerWorker.java, src/main/java/com/superzanti/serversync/util/PathUtils.java, src/main/java/com/superzanti/serversync/util/Server.java
Serversync would not check properly to see if it needs to run or not, minor due to this not really being a problem other than the possible confusion if serversync was run multiple times in a row.
=> Fix for minor checking problem

.gitignore, gradle.properties, src/main/java/com/superzanti/serversync/ClientWorker.java, src/main/java/com/superzanti/serversync/ServerWorker.java, src/main/java/com/superzanti/serversync/filemanager/FileManager.java, src/main/java/com/superzanti/serversync/util/PathBuilder.java, src/main/java/com/superzanti/serversync/util/PathUtils.java, src/main/java/com/superzanti/serversync/util/Server.java
I think this is a good addition to #73 but I cannot understand how do you save updates...
=> Messing around Minecraft directory gathering

.travis.yml, build.gradle, gradle.properties, src/main/java/com/superzanti/serversync/RefStrings.java, src/main/java/com/superzanti/serversync/client/ClientWorker.java, src/main/java/com/superzanti/serversync/filemanager/FileManager.java, src/main/java/com/superzanti/serversync/server/ServerSetup.java, src/main/java/com/superzanti/serversync/util/PathUtils.java, src/main/resources/assets/serversync/lang/MessagesBundle_en_US.properties
May alleviate some of the null pointer issues seen when trying to fetch files at startup.
=> Move some exception handling

src/main/java/runme/Main.java, src/main/resources/assets/serversync/lang/MessagesBundle_pl_PL.properties
And I've also fixed loading of `ResourceBundle`s
=> Polish translation

build.gradle, gradle.properties, src/main/java/com/superzanti/serversync/RefStrings.java, src/main/java/com/superzanti/serversync/client/ClientWorker.java, src/main/java/com/superzanti/serversync/config/IgnoredFilesMatcher.java, src/main/java/com/superzanti/serversync/server/Server.java, src/test/java/com/superzanti/serversync/util/GlobPathMatcherTests.java
Should assist with long load times for large amounts of files.
Should also speed up syncs as we don't need to hash ignored files or files that will be deleted.
=> Update client to hash files JIT

src/main/java/com/superzanti/serversync/server/ServerSetup.java
Should actually include configs now.
=> Fix config include list

src/main/java/com/superzanti/serversync/server/Server.java
Configs in the include list would always transfer to the client regardless of changes.
=> Fix config always sync

gradle.properties, src/main/java/com/superzanti/serversync/RefStrings.java, src/main/java/com/superzanti/serversync/server/ServerWorker.java
Server never resets the client timeout if the client only responds with "I already have the file"
=> #160 Fix server timing out clients during sync

README.md, build.gradle, src/main/java/com/superzanti/serversync/SyncConfig.java, src/main/java/com/superzanti/serversync/util/minecraft/config/FriendlyConfigElement.java, src/main/java/com/superzanti/serversync/util/minecraft/config/FriendlyConfigReader.java, src/main/java/com/superzanti/serversync/util/minecraft/config/FriendlyConfigWriter.java
Supports working in Eclipse should anyone desire to do so.
=> #162 Add eclipse plugin to gradle

config-server-schema.json, gradle.properties, src/main/java/com/superzanti/serversync/RefStrings.java, src/main/java/com/superzanti/serversync/ServerSync.java, src/main/java/com/superzanti/serversync/client/Mode2Sync.java, src/main/java/com/superzanti/serversync/config/ConfigLoader.java, src/main/java/com/superzanti/serversync/config/IgnoredFilesMatcher.java, src/main/java/com/superzanti/serversync/config/JsonConfig.java, src/main/java/com/superzanti/serversync/config/SyncConfig.java, src/main/java/com/superzanti/serversync/files/FileEntry.java, src/main/java/com/superzanti/serversync/files/FileManager.java, src/main/java/com/superzanti/serversync/files/FileRedirect.java, src/main/java/com/superzanti/serversync/server/ServerSetup.java, src/main/java/com/superzanti/serversync/util/Glob.java, src/test/java/com/superzanti/serversync/util/GlobPathMatcherTests.java, src/test/resources/server-config.json
Merges the changes for alpha 6
=> Merge alpha 6

src/main/java/com/superzanti/serversync/GUIJavaFX/PaneLogs.java, src/main/java/com/superzanti/serversync/ServerSync.java, src/main/java/com/superzanti/serversync/server/ServerWorker.java, src/main/java/com/superzanti/serversync/util/Logger.java, src/main/java/com/superzanti/serversync/util/LoggerInstance.java, src/test/java/com/superzanti/serversync/SyncConfigTests.java, src/test/java/com/superzanti/serversync/server/ServerSetupTests.java, src/test/java/com/superzanti/serversync/util/BannedIPSReaderTest.java, src/test/java/com/superzanti/serversync/util/GlobPathMatcherTests.java
After some sleep (and work) I've revisited the logger and did some refactoring to make it work, again, with client-specific logging, so now both static and instanced logging is possible by utilizing thread-safe singleton.
=> some love to the logger [S01E02]

src/main/java/com/superzanti/serversync/util/LoggerInstance.java
make logger log in one line for better readability
=> Some love to the logger [S01E03]

src/main/java/com/superzanti/serversync/communication/SyncFileOutputStream.java, src/main/java/com/superzanti/serversync/server/ServerWorker.java, src/main/java/com/superzanti/serversync/util/LoggerInstance.java
Fixes #241
Also prints out progress log when in `--quiet` mode, a handy way to know it's not stuck, it's working, albeit slow.
=> Remedies download timeout

src/main/java/com/superzanti/serversync/RefStrings.java, src/main/java/com/superzanti/serversync/ServerSync.java, src/main/java/com/superzanti/serversync/client/Mode2Sync.java, src/main/java/com/superzanti/serversync/util/Logger.java, src/main/java/com/superzanti/serversync/util/LoggerInstance.java, src/main/resources/assets/serversync/lang/MessagesBundle.properties
- Fixed crash when files were ignored client side
- Fixed file ignore patterns matching
- Changed debug logging to Level.FINE
=> Fix issues with release 4.0.0

src/main/java/com/superzanti/serversync/config/JsonConfig.java
JSON config entries changed between 3.7 and 4, this catches that change and upgrades to the new format.
=> #230 Add catch for missing config entries

gradle.properties, src/main/java/com/superzanti/serversync/RefStrings.java, src/main/java/com/superzanti/serversync/client/Server.java, src/main/java/com/superzanti/serversync/communication/SyncFileOutputStream.java, src/main/java/com/superzanti/serversync/config/JsonConfig.java, src/main/java/com/superzanti/serversync/config/SyncConfig.java, src/main/java/com/superzanti/serversync/server/ServerSetup.java, src/main/java/com/superzanti/serversync/server/ServerWorker.java, src/test/resources/server-config.json
Object*Stream seems to have garbage performance
=> Try using raw streams

src/main/java/com/superzanti/serversync/GUIJavaFX/PaneLogs.java, src/main/java/com/superzanti/serversync/GUIJavaFX/PaneProgressBar.java, src/main/java/com/superzanti/serversync/GUIJavaFX/PaneSync.java, src/main/java/com/superzanti/serversync/communication/Requests.java, src/main/java/com/superzanti/serversync/util/Logger.java, src/main/resources/assets/serversync/lang/MessagesBundle.properties
Cleaned out some UI update spamming for when connections are fast enough to notice.
=> UI optimizations
